Fix missing import in gtk/window.rs (#2011)
Cherry-picked from jpochyla/druid@a9522f5 .

Otherwise building jpochyla/psst on Linux or OpenBSD fails:
```
error[E0433]: failed to resolve: use of undeclared type `XcbHandle`
   --> /home/kn/src/druid/druid-shell/src/backend/gtk/window.rs:118:30
    |
118 |         RawWindowHandle::Xcb(XcbHandle::empty())
    |                              ^^^^^^^^^ not found in this scope
    |
```

This code was introduced in 11eb259ffd2f898c66883995d59c221f87569ac2 which
seems to target Windows and Mac but not Linux, so I assume that is why it
went unnoticed.

Co-authored-by: Jan Pochyla <jpochyla@gmail.com>